descriptor-schema-version: "2.10"

info:
  name: "portposter"
  description: "forwards COM port data to 177"
  version: "1.0"
  author-link: "http://www.airistaflow.com"
  author-name: "Airista"
 
app:
 # Refer Platform Support Matrix table.
 # armv7l for 32 bit CPU Architecture.
 # aarch64 for 64 bit CPU Architecture.
  cpuarch: armv71
  type: docker
 
  resources:
    profile: c1.small
    devices:
    - type: serial
      alias: usb
      label: HOST_DEV
      usage: Serial device of USB port of AP
    network:
      -
        interface-name: eth0

  # Specify runtime and startup
  startup:
    rootfs: rootfs.img
    target: /usr/bin/main 1>/dev/null 2>/dev/null